; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pro8MHzatmega328]
platform = atmelavr
board = pro8MHzatmega328
framework = arduino
lib_deps =
    MD_AD9833
    neu-rah/ArduinoMenu library@^4.21.4
    adafruit/Adafruit ST7735 and ST7789 Library@^1.8.1
    adafruit/Adafruit BusIO@^1.10.1
    Wire
    TimerOne
    ClickEncoder
    ; neu-rah/ArduinoMenu library@^4.21.4
lib_ignore = 
    SD

